---
version: "2.0"

services:
  node1:
    image: paullovette/cgb_validator_gbt_orch50
    env:
      - MONIKER=<NAME_OF_YOUR_VALIDATOR>
      - CHAIN_BINARY=https://cgb.s3.filebase.com/gravity
      - GENESIS_URL=https://cgb.s3.filebase.com/genesis.json
      - CHAIN_ID=<CHAIN_ID_DEPLOYING_TO>
      - P2P_SEEDS=
      - P2P_PERSISTENT_PEERS=
      - STATESYNC_RPC_SERVERS=
      - VALIDATOR_KEY_NAME=skynet-val
      - ORCHESTRATOR_KEY_NAME=skynet-orch
      - NODE_TYPE=validator
      - NODE_P2P_PEX=false
      - NODE_UNCONDITIONAL_PEER_IDS=
      - NODE_ADDR_BOOK_STRICT=false
      - NODE_DOUBLE_SIGN_CHECK_HEIGHT=10
      - ETHEREUM_RPC_NODE=http://testnet2.althea.net:8545
      - EHEREUM_ADDRESS_FUNDED=
      - ETHEREUM_PRIVATE_KEY=
      - ETHEREUM_CONTRACT_ADDRESS=0xace45Cd2d490a0A180e50144D8dd0c7EB9A4215f
      - VALIDATOR_BOND_AMOUNT=1000000ugraviton
      - VALIDATOR_COMMISSION_RATE=0.10
      - VALIDATOR_MAX_COMMISSION_RATE=0.20
      - VALIDATOR_MAX_COMMISSION_CHANGE_RATE=0.01
      - VALIDATOR_MIN_SELF_DELEGATION=1
      - VALIDATOR_FEES=200ugraviton
      - VALIDATOR_DETAILS="<DESCRIPTION>"
      - VALIDATOR_SECURITY_CONTACT=<EMAIL_ADDREESS>
      - VALIDATOR_WEBSIE=<VALIDATOR_WEBSITE>
      - VALIDATOR_IDENTITY=<KEYBASE_ID>
      - ORCHESTRATOR_FEES=1ufootoken
      - REMOTE_RPC_NODE=http://0.0.0.0:26657
      - S3_KEY=
      - S3_SECRET=
      - S3_HOST=https://s3.filebase.com
      - KEY_PATH=
      - KEY_PASSWORD=
      - MINIMUM_GAS_PRICES=
      - PRUNING=default
    expose:
      - port: 26657
        as: 80
        to:
          - global: true

profiles:
  compute:
    node1:
      resources:
        cpu:
          units: 2
        memory:
          size: 8Gi
        storage:
          size: 150Gi
  placement:
    dcloud:
      attributes:
        host: akash
      pricing:
        node1:
          denom: uakt
          amount: 100

deployment:
  node1:
    dcloud:
      profile: node1
      count: 1
